---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[sbt-package::install]
    attributes:
